//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonations.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginDetails
    {
        public long Id { get; set; }
        public long DonorId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public int RoleId { get; set; }
    
        public virtual DonorDetails DonorDetails { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
