//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonations.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDonationHistory
    {
        public long Id { get; set; }
        public long DonorId { get; set; }
        public System.DateTime DonationDate { get; set; }
    
        public virtual DonorDetails DonorDetails { get; set; }
    }
}
